### ISSUE TITLE
Display all family sequences in trio analysis

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics-Lund/gens#143]

**Comment by dnil** [comment]
Duplicate with https://github.com/Clinical-Genomics-Lund/gens/issues/116?

**Comment by Jakob37** [comment]
> Duplicate with #116?

Yes, thanks, I'll close!

**Comment by dnil** [comment]
Have you found your way to the SciLifeLab slack btw @Jakob37? There is a tiny `#dev-gens` channel there that could use some company. 😄

**Comment by Jakob37** [comment]
> Have you found your way to the SciLifeLab slack btw @Jakob37? There is a tiny `#dev-gens` channel there that could use some company. 😄

Aha, no not yet! Sounds like I/we should join. Looks like I need a special invite though, as I don't have a scilifelab-email. Do you know who I should reach out to?

```
You can use any account with the domain:

    scilifelab.se
    scilifelab.uu.se
    bils.se
    nbis.se

Don’t have an email address from one of those domains?
Contact the workspace administrator at SciLifeLab for an invitation.
```

**Comment by Jakob37** [comment]
Found it, I'll email datacentre@scilifelab.se
