### ISSUE TITLE
Allow vertical zooming in interactive view

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics-Lund/gens#41]
Sometimes we see mosaic deletions/duplication (or in somatic cases, perhaps low frequency ones). This are quite difficult to see at the current -4 to 4 Y-scale 

See this for example:
![bild](https://user-images.githubusercontent.com/11991860/109261616-5cf7aa00-7800-11eb-9d15-59fca709cb5e.png)

It would be nice to have to possibility to zoom on the Y-level. I *think* that would improve things.

Perhaps it is possible to do this entirely on the client side?

**Comment by mhkc** [comment]
This would be a cool feature.

I wonder if we could just adjust the "y-scale" when the images are being blitted to get the zoom in effect or if it would look fuzzy.
